name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_ubuntu_20_04:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure and Make
        run: bash ./autogen.sh
      - name: Install
        run: sudo make install
      - name: Run Tests
        run: bash ./tests/tests.sh
