name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure and Make
        run: autoreconf -vfi && ./configure && make
      - name: Run Tests
        run: make test
  build_macos_10_15:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Configure and Make
        run: autoreconf -vfi && ./configure && make
      - name: Run Tests
        run: bash ./tests/tests.sh
